image: 'registry.gitlab.com/hahnbanach/docker-images/alpine-docker-sbt:1.0.0'

services:
  - docker:19.03.12-dind

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - echo "${CI_REGISTRY_PASSWORD}" | docker login -u ${CI_REGISTRY_USER} ${CI_REGISTRY} --password-stdin

build:
  stage: build
  script:
    - sbt test
    - sbt publish
  only:
    refs:
      - master
      - tags
